version: "3.7"

services:
    my-backend:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./index.js:/myfolder/index.js
            - ./email.js:/myfolder/email.js
            - ./phone.js:/myfolder/phone.js
        ports:
          - 3005:3005

    my-database:
        image: mongo:latest
        ports: 
          - 27117:27017